global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/alert_rules.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape your FastAPI service (bike-api)
  - job_name: "bike-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["bike-api:8080"]

  # Scrape node-exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
